# Generated by Django 5.1 on 2024-09-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moedas.movimentacao')),
                ('categoria', models.CharField(choices=[('A', 'Alimentação'), ('E', 'Educação'), ('L', 'Lazer'), ('M', 'Moradia'), ('S', 'Saúde'), ('T', 'Transporte'), ('O', 'Outros')], max_length=1)),
                ('forma_pagamento', models.CharField(choices=[('din', 'Dinheiro'), ('deb', 'Cartão de Débito'), ('cre', 'Cartão de Crédito'), ('pix', 'Pix'), ('out', 'Outros')], max_length=4)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
            bases=('moedas.movimentacao',),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moedas.movimentacao')),
                ('categoria', models.CharField(choices=[('S', 'Salário'), ('O', 'Outros')], max_length=1)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
            bases=('moedas.movimentacao',),
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
    ]
