# Generated by Django 5.1 on 2024-09-10 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0003_categoria_remove_despesa_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('D', 'Despesa'), ('R', 'Receita'), ('T', 'Transferência'), ('I', 'Investimento')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='despesa',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('D', 'Despesa'), ('R', 'Receita'), ('T', 'Transferência'), ('I', 'Investimento')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
