# Generated by Django 5.1 on 2024-09-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0004_categoria_tipo_despesa_pago_movimentacao_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('sigla', 'tipo')},
        ),
    ]
