# Generated by Django 5.1 on 2025-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0005_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, default='ph ph-package', max_length=50),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='pago',
            field=models.BooleanField(default=True),
        ),
    ]
