# Generated by Django 5.1 on 2025-05-13 20:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0006_alter_categoria_icone_alter_despesa_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de gastos')),
                ('percentual_investimentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de investimentos')),
                ('percentual_dividas', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual para pagamento de dívidas')),
                ('percentual_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual para reserva de emergência')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estratégia',
                'verbose_name_plural': 'Estratégias',
                'db_table': 'estrategia',
                'ordering': ['user'],
            },
        ),
    ]
