# Generated by Django 5.1 on 2025-06-18 23:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0007_estrategia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Percentual de Limite de gastos')),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_mensal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento Mensal',
                'verbose_name_plural': 'Orçamentos Mensais',
                'db_table': 'orcamento_mensal',
                'ordering': ['user'],
            },
        ),
    ]
