# Generated by Django 5.1 on 2025-07-28 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0008_orcamentomensal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('nome', models.CharField(choices=[('001', 'Banco do Brasil'), ('033', 'Santander'), ('104', 'Caixa Econômica Federal'), ('237', 'Bradesco'), ('341', 'Itaú Unibanco'), ('399', 'HSBC'), ('745', 'Citibank'), ('756', 'Bancoob'), ('104', 'Caixa Econômica Federal'), ('070', 'Banco Inter')], max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
