# Generated by Django 5.1 on 2025-08-19 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0009_contabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispb', models.CharField(help_text='Identificador do Sistema de Pagamentos Brasileiro', max_length=8, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('abreviacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='nome',
            field=models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('033', 'Santander'), ('104', 'Caixa Econômica Federal'), ('237', 'Bradesco'), ('341', 'Itaú Unibanco'), ('399', 'HSBC'), ('745', 'Citibank'), ('756', 'Bancoob'), ('104', 'Caixa Econômica Federal'), ('070', 'Banco Inter')], default='001', max_length=100),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='moedas.banco'),
        ),
    ]
