# Generated by Django 5.1 on 2025-08-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0010_banco_alter_contabancaria_nome_contabancaria_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do banco, opcional.', null=True, upload_to='bancos/'),
        ),
    ]
