# Generated by Django 5.1 on 2025-09-18 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0011_banco_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='conta_bancaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moedas.contabancaria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('deb', 'Cartão de Débito'), ('cre', 'Cartão de Crédito'), ('pix', 'Pix'), ('out', 'Outros')], max_length=4),
        ),
    ]
