# Generated by Django 5.1 on 2025-11-26 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moedas', '0012_movimentacao_conta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='criado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='conta_bancaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='moedas.contabancaria'),
        ),
    ]
