target-version = "py312"
fix = true
src = ["var/app/"]
line-length = 100

[lint]
select = ["ALL"]
ignore = [
    "TD003", # Disable TODO issue
    "D100", # Missing docstring in public module
    "EXE002", # Use of `exec` statement
]

fixable = ["ALL"]